### ISSUE TITLE
Links to references.bib not working in notebook

### ISSUE THREAD

**Issue by awiawi** [StephanRhode/py-algorithms-4-automotive-engineering#19]
I found that the links referencing the references.bib file (for example here https://github.com/StephanRhode/py-algorithms-4-automotive-engineering/blame/master/01_basic-python/00_syntax.ipynb#L18) can not be resolved in notebook (on github and local).

The links reference the file `./references.bib` but the file is one folder up, so the link should point to `../references.bib`. Is there a maybe a problem with other tools if the links are pointing to `../references.bib`?

**Comment by StephanRhode** [comment]
This is a bug, which will be resolved through pull request #21.
