### ISSUE TITLE
Compatibility Issue: make_slides.py and Notebook Package Version 7.0.2

### ISSUE THREAD

**Issue by fabianwuest** [StephanRhode/py-algorithms-4-automotive-engineering#28]
Hi there,

It appears there's an incompatibility with the latest version of the notebook package (7.0.2) when running the make_slides script. When using this version of the package, I encountered an error, i.e. `ModuleNotFoundError: No module named 'notebook.base'.`

At the time the lecture notebooks were written, the notebook package was not yet at version > 7.

I resolved the issue by downgrading to version 6.5.5, after which the script worked perfectly. This information might be helpful for other students who encounter the same issue.

**Comment by StephanRhode** [comment]
Thanks for this hint. Yes, I have the same problem with other projects as well. The `notebook 7.0.2` seems to skip some base packages which were part of it since many years. I will change the `requirements.txt` file to prevent this bug.
