### ISSUE TITLE
DeepL notebook

### ISSUE THREAD

**Issue by StephanRhode** [StephanRhode/py-algorithms-4-automotive-engineering#8]
Hi @mauricio-fernandez-l ,

great that you are on board. I created the template notebook `04_mini-projects/09_deepl.ipynb` on branch deepl. This notebook has some default figures and is tested every time you push in Travis CI. The link to respective Travis is in readme and here for convenience [Travis for this repo](https://travis-ci.com/StephanRhode/py-algorithms-4-automotive-engineering/branches)

You can test all notebooks with pytest and you can create presentation slides with `make_slides.py` in root folder. All is described in readme. If you need additional python packages, please add them in `requirements.txt `.

With respect to topic, it would be nice if we could do something with traffic sign recognition, but feel free. Add to this, it would be great if the students could solve some small problems by themselves.

Please let me know if you struggle with the setup of this repo or need any support.

**Comment by mauricio-fernandez-l** [comment]
Hi Stephan!

Sorry for the delay. I will work on the lecture this and the next week. I checked out the `deepl` branch and will edit the notebook `04_mini-projects/09_deepl.ipynb`. I tested locally the script `make_slides.py` and everything works fine on my end. I will also add `tensorflow` to the `requirements.txt`.

With respect to the examples, I generated today some synthetic image data for traffic sign recognition. I think that will provide a good and relevant example for deep convolutional networks. I will keep you updated.

Best,

Mauricio

**Comment by StephanRhode** [comment]
Sounds great, just go ahead and me know if I can help somewhere.

**Comment by mauricio-fernandez-l** [comment]
@StephanRhode I just uploaded the draft for the lecture and created the pull request. Can you take a look into it when you have time?

**Comment by StephanRhode** [comment]
Is resolved in pull request #12
